apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rishabhxnandekar/devsecops-backend:v1-build-1
          ports:
            - containerPort: 5000
          env:
        - name: DB_HOST
          value: postgres

        - name: DB_PORT
          value: "5432"

        - name: DB_USER
          value: postgres

        - name: DB_NAME
          value: devsecops_pipeline

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password

      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"

        limits:
          cpu: "500m"
          memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000